//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrempBossDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tremp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tremp()
        {
            this.User_Tremps = new HashSet<User_Tremps>();
        }
    
        public int tremp_id { get; set; }
        public bool tremp_type { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime tremp_time { get; set; }
        public string note { get; set; }
        public int seats_amount { get; set; }
        public bool is_full { get; set; }
        public bool deleted { get; set; }
        public string from_route { get; set; }
        public string to_route { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Tremps> User_Tremps { get; set; }
    }
}
