//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrempBossDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Tremps
    {
        public int tremp_id { get; set; }
        public int user_id { get; set; }
        public bool created_ride { get; set; }
        public int group_id { get; set; }
        public string is_confirmed { get; set; }
    
        public virtual Tremp Tremp { get; set; }
        public virtual User User { get; set; }
    }
}
